In [13]:
import sys
sys.path.append("..")

import dataInterpreter as dt
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import scipy

## Select columns to analyse

In [14]:
colLabels = []
i = 0

colstmp = dt.get_columns('NHBE', 'healthy')
colLabels += [i] * len(colstmp)
i += 1
cols = colstmp

colstmp = dt.get_columns('NHBE', 'sars-cov2')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('NHBE', 'iav')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('NHBE', 'iavdns1')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp


colstmp = dt.get_columns('A549', 'healthy')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('A549', 'sars-cov2')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('A549', 'iav')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('A549', 'rsv')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('A549', 'hpiv3')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp


colstmp = dt.get_columns('Calu3', 'healthy')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('Calu3', 'sars-cov2')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp


colstmp = dt.get_columns('biopsy', 'healthy')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

colstmp = dt.get_columns('biopsy', 'sars-cov2')
colLabels += [i] * len(colstmp)
i += 1
cols += colstmp

In [15]:
pairs = [
    [dt.get_columns('NHBE', 'healthy', series = [1]),
     dt.get_columns('NHBE', 'sars-cov2', series = [1])],
    [dt.get_columns('NHBE', 'healthy', series = [9]),
     dt.get_columns('NHBE', 'iav', series = [9])],
    [dt.get_columns('NHBE', 'healthy', series = [9]),
     dt.get_columns('NHBE', 'iavdns1', series = [9])],
    
    [dt.get_columns('A549', 'healthy', series = [2, 5]),
     dt.get_columns('A549', 'sars-cov2', series = [2, 5])],
    [dt.get_columns('A549', 'healthy', series = [4]),
     dt.get_columns('A549', 'iav', series = [4])],
    [dt.get_columns('A549', 'healthy', series = [3]),
     dt.get_columns('A549', 'rsv', series = [3])],
    [dt.get_columns('A549', 'healthy', series = [8]),
     dt.get_columns('A549', 'hpiv3', series = [8])],
    
    [dt.get_columns('Calu3', 'healthy', series = [7]),
     dt.get_columns('Calu3', 'sars-cov2', series = [7])],
    
    [dt.get_columns('biopsy', 'healthy', series = [15]),
     dt.get_columns('biopsy', 'sars-cov2', series = [15])],
]

data = dt.get_complete_data()[cols]
data

In [16]:
j = 0
pvalues = {}

num_rows = len(data.index)

for index, row in data.iterrows():
    i = 0
    for pair in pairs:
        col_name = "p-value" + str(i)
        
        if col_name not in pvalues:
            pvalues[col_name] = []
        
        if not row[pair[0]].tolist() == row[pair[1]].tolist():
            pvalues[col_name] += [scipy.stats.levene(row[pair[0]], row[pair[1]]).pvalue]
        else:
            pvalues[col_name] += [1,]
            
        i += 1
    
    dt.printProgressBar(j, num_rows)
    
    j += 1

C:\Users\Pedro\anaconda3\lib\site-packages\scipy\stats\morestats.py:2417: RuntimeWarning: divide by zero encountered in double_scalars
  W = numer / denom

C:\Users\Pedro\anaconda3\lib\site-packages\scipy\stats\morestats.py:2417: RuntimeWarning: invalid value encountered in double_scalars
  W = numer / denom
C:\Users\Pedro\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1932: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)

 |===================================================================================================> ||===>                                                                                                 ||====>                                                                                                ||===========>                                                                                         ||===============>                                                                                     ||========================================>                                                            ||==============================================>                                                      ||====================================================>                                                ||====================================================>                                                ||=====================================================>                                               ||======================================================================>                              ||=======================================================================>                             |

In [41]:
a = np.array(pvalues['p-value0'])
a

array([1.        , 0.31576187, 0.16716621, ..., 1.        , 1.        ,
       1.        ])

In [43]:
pvalues.keys()

dict_keys(['p-value0', 'p-value1', 'p-value2', 'p-value3', 'p-value4', 'p-value5', 'p-value6', 'p-value7', 'p-value8'])

In [45]:
pvalue_data = pd.DataFrame(pvalues)

In [46]:
pvalue_data.insert(len(pvalue_data.columns), "min", pvalue_data.min(axis = 1))

In [47]:
pvalue_data

,p-value0,p-value1,p-value2,p-value3,p-value4,p-value5,p-value6,p-value7,p-value8,min
0,1.000000,1.000000,1.000000,0.144928,1.000000e+00,0.000000e+00,1.000000,0.373901,1.000000e+00,0.000000e+00
1,0.315762,0.172331,0.288851,0.771895,0.000000e+00,0.000000e+00,0.555298,0.354139,0.000000e+00,0.000000e+00
2,0.167166,0.250983,0.999145,0.684062,1.835034e-01,1.874635e-31,1.000000,0.353523,1.005797e-31,1.005797e-31
3,0.553937,0.289628,0.762979,0.737457,3.137285e-31,1.461905e-29,0.434627,0.314377,5.367852e-31,3.137285e-31
4,0.368679,0.733921,0.207031,0.805197,1.708042e-30,0.000000e+00,0.502364,0.382747,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
19962,1.000000,1.000000,1.000000,1.000000,0.000000e+00,1.000000e+00,1.000000,1.000000,0.000000e+00,0.000000e+00
19963,1.000000,1.000000,1.000000,0.107443,1.108296e-31,1.350319e-29,0.223486,1.000000,0.000000e+00,0.000000e+00
19964,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000,0.000000e+00,0.000000e+00
19965,1.000000,1.000000,1.000000,0.738760,7.556776e-31,0.000000e+00,0.177527,1.000000,0.000000e+00,0.000000e+00
19966,1.000000,1.000000,1.000000,0.340893,1.000000e+00,0.000000e+00,1.000000,1.000000,0.000000e+00,0.000000e+00

In [51]:
pvalue_data.loc[pvalue_data['min'] < 0.01]

,p-value0,p-value1,p-value2,p-value3,p-value4,p-value5,p-value6,p-value7,p-value8,min
0,1.000000,1.000000,1.000000,0.144928,1.000000e+00,0.000000e+00,1.000000,0.373901,1.000000e+00,0.000000e+00
1,0.315762,0.172331,0.288851,0.771895,0.000000e+00,0.000000e+00,0.555298,0.354139,0.000000e+00,0.000000e+00
2,0.167166,0.250983,0.999145,0.684062,1.835034e-01,1.874635e-31,1.000000,0.353523,1.005797e-31,1.005797e-31
3,0.553937,0.289628,0.762979,0.737457,3.137285e-31,1.461905e-29,0.434627,0.314377,5.367852e-31,3.137285e-31
4,0.368679,0.733921,0.207031,0.805197,1.708042e-30,0.000000e+00,0.502364,0.382747,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
19962,1.000000,1.000000,1.000000,1.000000,0.000000e+00,1.000000e+00,1.000000,1.000000,0.000000e+00,0.000000e+00
19963,1.000000,1.000000,1.000000,0.107443,1.108296e-31,1.350319e-29,0.223486,1.000000,0.000000e+00,0.000000e+00
19964,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000,0.000000e+00,0.000000e+00
19965,1.000000,1.000000,1.000000,0.738760,7.556776e-31,0.000000e+00,0.177527,1.000000,0.000000e+00,0.000000e+00
19966,1.000000,1.000000,1.000000,0.340893,1.000000e+00,0.000000e+00,1.000000,1.000000,0.000000e+00,0.000000e+00